### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by llwor94** [likeconan/react-avatar-image-cropper#9]
I get this error when trying to use the component.

**Comment by likeconan** [comment]
Can you please show me the code? so that I can help with that @llwor94

**Comment by JosephKrebs** [comment]
I'd just like to mention that this issue occurs with Next.js due to the component being rendered serverside. You can workaround this by importing it as:

`const AvatarImageCropper = dynamic(
  () => import('react-avatar-image-cropper').then((mod) => mod.default),
  { ssr: false }
)`

Don't forget to import next/dynamic:

`import dynamic from 'next/dynamic'`
